#!/usr/bin/env python3
"""
percept_demo.py — replay a simulated scenario into the drivelive minimap.

The minimap is only as good as it is legible under load, and that cannot be
judged from a screenshot of an empty radar. This serves the same websocket
protocol as cartlib.server, but broadcasts nothing except ``perception``
frames, generated by running one of the collision-avoidance scenarios from the
test suite in real time.

So the picture on screen is not a mock-up: it is the same geometry, the same
tracker and the same policy the safety tests run against, at wall-clock speed.
A track that goes dashed really has lost its detection; a disc that swells
really is a range estimate falling apart near the horizon.

Usage
-----
    python3 tools/percept_demo.py --scenario crossing
    python3 tools/percept_demo.py --list

The live cart server owns port 8765, so either stop it and run the demo on the
default port, or leave it up and give the demo its own:

    python3 tools/percept_demo.py --port 8766
    # then, in the drivelive shell:
    NEXT_PUBLIC_GPS_WS_URL=ws://localhost:8766 npm run dev

The second form shows the minimap without the map feed, which is the right
trade when the thing being checked IS the minimap.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import math
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "tests"))

import websockets  # noqa: E402

import percept_sim as S  # noqa: E402
from cartlib.percept.geometry import project_detection  # noqa: E402
from cartlib.percept.policy import Governor, PolicyConfig  # noqa: E402
from cartlib.percept.telemetry import perception_payload  # noqa: E402
from cartlib.percept.track import EgoPose, Tracker  # noqa: E402

WS_PORT = 8765
WALK, RUN, CARSPD = 1.4, 3.0, 11.0

SCENARIOS = {
    "standing": ("someone standing in the path",
                 lambda: ([S.Actor("person", 0.0, 22.0)], S.straight_route())),
    "crossing": ("pedestrian crossing left to right",
                 lambda: ([S.Actor("person", -6.0, 20.0, vx=WALK)],
                          S.straight_route())),
    "stepout": ("pedestrian steps out from behind a parked car",
                lambda: ([S.Actor("car", -2.6, 21.0),
                          S.Actor("person", -2.6, 20.6, vx=WALK, t_start=2.0)],
                         S.straight_route())),
    "busy": ("mixed campus traffic",
             lambda: ([S.Actor("person", 2.4, 18.0),
                       S.Actor("person", 3.1, 19.0),
                       S.Actor("person", -7.0, 26.0, vx=WALK),
                       S.Actor("car", -3.0, 40.0),
                       S.Actor("bicycle", -2.0, 34.0, vy=-RUN)],
                      S.straight_route(90.0))),
    "car": ("car crossing at 25 mph",
            lambda: ([S.Actor("car", -45.0, 26.0, vx=CARSPD)],
                     S.straight_route())),
    "bend": ("someone on the inside of a bend",
             lambda: ([S.Actor("person", 3.2, 22.5)],
                      S.Route([(0, 0), (0, 18), (8, 30), (8, 60)]))),
}

_clients: set = set()


async def _handler(ws):
    _clients.add(ws)
    try:
        async for _ in ws:
            pass
    except Exception:
        pass
    finally:
        _clients.discard(ws)


async def _broadcast(obj: dict) -> None:
    if not _clients:
        return
    msg = json.dumps(obj)
    await asyncio.gather(*[c.send(msg) for c in list(_clients)],
                         return_exceptions=True)


async def _run(name: str, loop_forever: bool) -> None:
    cfg = PolicyConfig()
    sim = S.SimConfig()
    cam = S.CameraModel(width=1920, height=1200, fx=1000.0, fy=1000.0,
                        dist=(-0.28, 0.09, 0.0, 0.0, 0.0), height_m=1.45,
                        pitch_deg=6.0, offset_forward_m=1.6, pitch_sigma_deg=1.0)
    import random

    while True:
        desc, build = SCENARIOS[name]
        actors, route = build()
        print(f"[demo] {name}: {desc}")
        rng = random.Random(7)
        tracker = Tracker()
        gov = Governor(cfg, initial_mph=cfg.max_speed_mph)
        route_xy = list(route.pts)
        s, v_ms = 0.0, cfg.max_speed_mph / 2.2369363
        t = 0.0
        t0 = time.monotonic()

        while t < 30.0:
            x, y, heading = route.at(s)
            ego = EgoPose(x=x, y=y, heading_deg=heading, speed_ms=v_ms, ts=t)
            pitch = cam.pitch_deg + rng.gauss(0.0, sim.pitch_wobble_deg)
            boxes = S.render_frame(cam, ego, actors, t, pitch, rng,
                                   jitter_px=sim.jitter_px)
            dets = []
            for b in boxes:
                d = project_detection(cam, b.bbox, b.cls, b.conf)
                if d is not None:
                    dets.append(d)
            tracks = tracker.update(dets, ego, t)
            v_cmd = gov.step(tracks, route_xy, ego, t, sim.dt)

            # Plant: same first-order lag and transport delay the tests use.
            v_want = v_cmd / 2.2369363
            a = (v_want - v_ms) / sim.plant_tau_s
            a = max(-sim.plant_decel_ms2, min(a, sim.plant_accel_ms2))
            v_ms = max(0.0, v_ms + a * sim.dt)
            s = min(s + v_ms * sim.dt, route.length)

            await _broadcast({"type": "perception", "data": perception_payload(
                tracks, gov.decision, ego, cfg,
                detector_hz=1.0 / sim.dt, frame_age_s=sim.dt,
                ts=time.time(), shadow=True, fov_deg=cam.hfov_deg())})

            t += sim.dt
            await asyncio.sleep(max(0.0, t0 + t - time.monotonic()))

        if not loop_forever:
            return
        await asyncio.sleep(1.5)


async def _main(args) -> None:
    try:
        server = await websockets.serve(_handler, "", args.port, ping_interval=20)
    except OSError as e:
        print(f"[demo] cannot bind port {args.port}: {e}\n"
              f"       the live cart server probably has it. Either stop it, or\n"
              f"       run:  python3 tools/percept_demo.py --port {args.port + 1}")
        return
    async with server:
        print(f"[demo] websocket on ws://localhost:{args.port} — open the UI")
        await _run(args.scenario, args.loop)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--scenario", default="busy", choices=sorted(SCENARIOS))
    ap.add_argument("--port", type=int, default=WS_PORT)
    ap.add_argument("--loop", action="store_true", default=True)
    ap.add_argument("--once", dest="loop", action="store_false")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()

    if args.list:
        for k, (desc, _) in sorted(SCENARIOS.items()):
            print(f"  {k:10s} {desc}")
        return 0
    try:
        asyncio.run(_main(args))
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
